version: "3.9"
services:
  nest:
    build: .
    image: nest
    ports:
      - "8888:5000"
    volumes:
      - .:/usr/src/nest
    depends_on:
      - db
  db:
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: user
        POSTGRES_DB: db_nest
      image: postgres:latest
      networks:
        - default
      ports:
        - 5432:5432
      restart: always
      volumes:
        - ./postgres:/var/lib/postgresql/data